# Generated by Django 4.2.2 on 2023-06-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('rated', models.CharField(max_length=20)),
                ('released', models.CharField(max_length=20)),
                ('runtime', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=200)),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('award', models.TextField()),
                ('poster', models.TextField()),
                ('ratings', models.TextField()),
                ('metascore', models.CharField(max_length=20)),
                ('imdbrating', models.CharField(max_length=20)),
                ('imdbvote', models.CharField(max_length=20)),
                ('imdbID', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('dvd', models.CharField(max_length=20)),
                ('boxoffice', models.CharField(max_length=20)),
                ('production', models.CharField(max_length=100)),
                ('website', models.TextField()),
                ('response', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
